"""empty message

Revision ID: 151d5a4c43a8
Revises: 357c92da35b9
Create Date: 2024-11-15 19:45:05.704480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151d5a4c43a8'
down_revision = '357c92da35b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mass', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('unit_heigth', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('unit_mass', sa.String(length=250), nullable=False))
        batch_op.drop_column('lightsaber')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_period', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('surface_water', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('diameter')
        batch_op.drop_column('surface_water')
        batch_op.drop_column('rotation_period')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lightsaber', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('unit_mass')
        batch_op.drop_column('unit_heigth')
        batch_op.drop_column('mass')

    # ### end Alembic commands ###
